version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/allbadeum-batch-server
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/shutdown.sh
  AfterInstall:
    - location: scripts/startup.sh
